name: build

on: [push]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: '.nvmrc'
        registry-url: 'https://registry.npmjs.org'
    - name: Enable Corepack
      run: corepack enable
    - name: Get pnpm store path
      id: pnpm-store
      run: echo "path=$(pnpm store path --silent)" >> "$GITHUB_OUTPUT"
    - name: Cache pnpm store
      uses: actions/cache@v4
      with:
        path: ${{ steps.pnpm-store.outputs.path }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-
    - name: Deploy Info
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: Install
      run: pnpm install --frozen-lockfile
    - name: Build
      run: pnpm build
    - name: Test
      run: pnpm test
    - name: Build Demo
      run: pnpm build-site
    - name: Publish
      if: startsWith(github.ref, 'refs/tags/')
      run: pnpm package
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
    - name: Publish Demo
      uses: JamesIves/github-pages-deploy-action@v4.3.0
      if: startsWith(github.ref, 'refs/tags/')
      with:
        branch: gh-pages
        folder: packages/website/out
        commit-message: Updates
